package eu.boxwor.dhbw.examples.test.webservice;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import eu.boxwork.dhbw.examples.webservice.HelloToSend;
import eu.boxwork.dhbw.examples.webservice.Service;

import static org.junit.Assert.*;

public class ServiceTest {
    @Test public void testHello() {
    	Service service = new Service();
        assertEquals("hello!!!", service.hello());
    }
    
    @Test public void helloWorldJSON() {
    	Service service = new Service();
    	String myName = "testname";
    	FileHandler resp = service.helloWorldJSON(myName);
        assertEquals(resp.getName(), myName);
    }
    
    @Test public void helloWorldText() {
    	Service service = new Service();
    	String myName = "testname";
    	FileHandler resp = service.helloWorldText(myName);
        assertEquals(resp.getName(), myName);
    }
}
